using System.Globalization;
using System.Text;

namespace Bennewitz.Ninja.XamlQuality.ThemeAudit;

/// <summary>
/// Renders an <see cref="AuditResult"/> as the Markdown report a repository commits. The output
/// is a pure function of the inputs — ordinal ordering, invariant number formatting, LF line
/// endings, paths relative to the configuration file, no timestamps — so a fresh run equals the
/// committed file until a pin moves.
/// </summary>
public static class MarkdownReport
{
    private const string None = "_none_";

    /// <summary>Renders the report.</summary>
    public static string Render(AuditResult result)
    {
        StringBuilder sb = new();
        AuditConfig config = result.Config;

        sb.Append("# ").Append(config.Title).Append("\n\n");
        sb.Append("Generated by `theme-audit report` from `").Append(Path.GetFileName(config.ConfigPath))
          .Append("`. Regenerate it with the same command after a pin bump; `theme-audit report --check` fails ")
          .Append("when this file no longer matches a fresh run. Paths are relative to the configuration file; ")
          .Append("a digest covers the files read, so the report changes exactly when its inputs do.\n\n");

        RenderThemes(sb, result);
        RenderConsumers(sb, result);
        RenderUndefined(sb, result);
        RenderContrast(sb, result);
        RenderCompat(sb, result);

        return sb.ToString();
    }

    private static void RenderCompat(StringBuilder sb, AuditResult result)
    {
        if (result.Compat.Count == 0)
        {
            return;
        }

        sb.Append("## Compat dictionaries\n\n");
        sb.Append("Generated by `theme-audit compat`: for each target variant, every key the source theme defines that ")
          .Append("the target lacks. A mapped key aliases the target's own token per the reviewed mapping; a copied key ")
          .Append("carries the source's definition verbatim; a literal is a colour written out because its source alias ")
          .Append("would dangle — the review set; a restored key is one the target's own variant defines, put back over ")
          .Append("the inherited entry so the dictionary never shadows the theme.\n\n");

        sb.Append("| Dictionary | From → To | Mapping | Output | Mapped | Copied | Literal | Restored | Skipped |\n|---|---|---|---|---:|---:|---:|---:|---:|\n");
        foreach (CompatOutcome outcome in result.Compat)
        {
            int Count(CompatHow how) => outcome.Generation.Entries.Count(e => e.How == how);
            sb.Append("| ").Append(Cell(outcome.Config.Name))
              .Append(" | ").Append(Cell(outcome.Config.From)).Append(" → ").Append(Cell(outcome.Config.To))
              .Append(" | ").Append(Code(outcome.Mapping.Name))
              .Append(" | ").Append(Code(outcome.Config.Output))
              .Append(" | ").Append(Count(CompatHow.Mapped).ToString(CultureInfo.InvariantCulture))
              .Append(" | ").Append(Count(CompatHow.Copied).ToString(CultureInfo.InvariantCulture))
              .Append(" | ").Append(Count(CompatHow.Literal).ToString(CultureInfo.InvariantCulture))
              .Append(" | ").Append(Count(CompatHow.Restored).ToString(CultureInfo.InvariantCulture))
              .Append(" | ").Append(outcome.Generation.Skipped.Count.ToString(CultureInfo.InvariantCulture))
              .Append(" |\n");
        }

        sb.Append('\n');

        foreach (CompatOutcome outcome in result.Compat)
        {
            sb.Append("### ").Append(outcome.Config.Name).Append("\n\n");

            RenderEntryGroup(sb, outcome, CompatHow.Mapped, "Mapped", "Target");
            RenderEntryGroup(sb, outcome, CompatHow.Literal, "Literal (review)", "Written because");
            RenderEntryGroup(sb, outcome, CompatHow.Restored, "Restored", "From");

            List<IGrouping<string, CompatEntry>> copiedKinds = outcome.Generation.Entries
                .Where(e => e.How == CompatHow.Copied)
                .GroupBy(e => e.Detail, StringComparer.Ordinal)
                .OrderByDescending(g => g.Count())
                .ThenBy(g => g.Key, StringComparer.Ordinal)
                .ToList();
            if (copiedKinds.Count > 0)
            {
                sb.Append("**Copied verbatim**, by element kind (entries across all variants):\n\n| Element | Entries |\n|---|---:|\n");
                foreach (IGrouping<string, CompatEntry> kind in copiedKinds)
                {
                    sb.Append("| ").Append(Code(kind.Key)).Append(" | ").Append(kind.Count().ToString(CultureInfo.InvariantCulture)).Append(" |\n");
                }

                sb.Append('\n');
            }

            List<IGrouping<(string Key, string Reason), CompatSkipped>> skipped = outcome.Generation.Skipped
                .GroupBy(s => (s.Key, s.Reason))
                .OrderBy(g => g.Key.Key, StringComparer.Ordinal)
                .ToList();
            if (skipped.Count > 0)
            {
                sb.Append("**Skipped**:\n\n| Key | Variants | Reason |\n|---|---|---|\n");
                foreach (IGrouping<(string Key, string Reason), CompatSkipped> group in skipped)
                {
                    sb.Append("| ").Append(Code(group.Key.Key))
                      .Append(" | ").Append(Cell(string.Join(", ", group.Select(s => s.Variant))))
                      .Append(" | ").Append(Cell(group.Key.Reason))
                      .Append(" |\n");
                }

                sb.Append('\n');
            }
        }
    }

    private static void RenderEntryGroup(StringBuilder sb, CompatOutcome outcome, CompatHow how, string title, string detailHeading)
    {
        List<IGrouping<(string Key, string Detail), CompatEntry>> groups = outcome.Generation.Entries
            .Where(e => e.How == how)
            .GroupBy(e => (e.Key, e.Detail))
            .OrderBy(g => g.Key.Key, StringComparer.Ordinal)
            .ToList();
        if (groups.Count == 0)
        {
            return;
        }

        sb.Append("**").Append(title).Append("**:\n\n| Key | Variants | ").Append(detailHeading).Append(" |\n|---|---|---|\n");
        foreach (IGrouping<(string Key, string Detail), CompatEntry> group in groups)
        {
            sb.Append("| ").Append(Code(group.Key.Key))
              .Append(" | ").Append(Cell(string.Join(", ", group.Select(e => e.Variant))))
              .Append(" | ").Append(Cell(group.Key.Detail))
              .Append(" |\n");
        }

        sb.Append('\n');
    }

    private static void RenderThemes(StringBuilder sb, AuditResult result)
    {
        AuditConfig config = result.Config;

        sb.Append("## Themes\n\n");
        sb.Append("| Theme | Entry | Files | Digest | Variants audited |\n|---|---|---:|---|---|\n");
        foreach (ThemeTarget theme in result.Themes)
        {
            string entry = config.Relative(config.Resolve(theme.Config.Entry!));
            string merge = theme.Config.Merge is { Count: > 0 } merged
                ? " + " + string.Join(" + ", merged.Select(m => Code(m)))
                : string.Empty;
            sb.Append("| ").Append(Cell(theme.Config.Name))
              .Append(" | ").Append(Code(entry)).Append(merge)
              .Append(" | ").Append(theme.Inventory.Files.Count.ToString(CultureInfo.InvariantCulture))
              .Append(" | ").Append(Code(theme.Digest))
              .Append(" | ").Append(Cell(string.Join(", ", theme.Variants)))
              .Append(" |\n");
        }

        sb.Append("\n### Variants\n\n");
        sb.Append("| Theme | Variant | Resolves as | Keys | Colours | Page | Text |\n|---|---|---|---:|---:|---|---|\n");
        foreach (ThemeTarget theme in result.Themes)
        {
            foreach (string variantName in theme.Variants)
            {
                VariantInventory variant = theme.Inventory.ForVariant(variantName);
                int colours = variant.Keys.Count(k => variant.Resolve(k) is not null);
                sb.Append("| ").Append(Cell(theme.Config.Name))
                  .Append(" | ").Append(Cell(variantName))
                  .Append(" | ").Append(Cell(variant.DisplayName))
                  .Append(" | ").Append(variant.Keys.Count.ToString(CultureInfo.InvariantCulture))
                  .Append(" | ").Append(colours.ToString(CultureInfo.InvariantCulture))
                  .Append(" | ").Append(Surface(theme, variantName, variant, "Page"))
                  .Append(" | ").Append(Surface(theme, variantName, variant, "Text"))
                  .Append(" |\n");
            }
        }

        sb.Append("\n### Unresolved includes\n\n");
        List<(string Theme, UnresolvedInclude Include)> unresolved = result.Themes
            .SelectMany(t => t.Inventory.Unresolved.Select(u => (t.Config.Name, u)))
            .ToList();
        if (unresolved.Count == 0)
        {
            sb.Append(None).Append('\n');
        }
        else
        {
            sb.Append("| Theme | In | Source | Reason |\n|---|---|---|---|\n");
            foreach ((string themeName, UnresolvedInclude include) in unresolved)
            {
                sb.Append("| ").Append(Cell(themeName))
                  .Append(" | ").Append(Code(RelativeIfInside(config, include.SourceFile)))
                  .Append(" | ").Append(Code(include.Source))
                  .Append(" | ").Append(Cell(include.Reason))
                  .Append(" |\n");
            }
        }

        sb.Append('\n');
    }

    private static string Surface(ThemeTarget theme, string variantName, VariantInventory variant, string placeholder)
    {
        string? key = theme.Surfaces.Resolve(variantName, placeholder);
        if (key is null)
        {
            return "—";
        }

        AuditColor? colour = variant.Resolve(key);
        return Code(key) + " " + (colour?.ToString() ?? "(no colour)");
    }

    private static void RenderConsumers(StringBuilder sb, AuditResult result)
    {
        sb.Append("## Consumers\n\n");
        sb.Append("| Consumer | Directories | Files | References | Distinct keys | Own keys | Digest | Audited against |\n|---|---|---:|---:|---:|---:|---|---|\n");
        foreach (ConsumerScan consumer in result.Consumers)
        {
            string directories = string.Join(", ", consumer.Config.Paths.Select(p => Code(p.Display)));
            string against = consumer.Config.Themes is { } only
                ? string.Join(", ", only)
                : "all";
            sb.Append("| ").Append(Cell(consumer.Config.Name))
              .Append(" | ").Append(directories)
              .Append(" | ").Append(consumer.Files.Count.ToString(CultureInfo.InvariantCulture))
              .Append(" | ").Append(consumer.References.Count.ToString(CultureInfo.InvariantCulture))
              .Append(" | ").Append(consumer.References.Select(r => r.Key).Distinct(StringComparer.Ordinal).Count().ToString(CultureInfo.InvariantCulture))
              .Append(" | ").Append(consumer.OwnKeys.Count.ToString(CultureInfo.InvariantCulture))
              .Append(" | ").Append(Code(consumer.Digest))
              .Append(" | ").Append(Cell(against))
              .Append(" |\n");
        }

        sb.Append('\n');
    }

    private static void RenderUndefined(StringBuilder sb, AuditResult result)
    {
        sb.Append("## Undefined keys\n\n");
        sb.Append("A key a consumer references that the theme does not define under a variant. A `DynamicResource` ")
          .Append("reference resolves to nothing and paints an invisible control; a `StaticResource` reference throws ")
          .Append("when the template loads. \"all\" means every audited variant lacks the key.\n\n");

        sb.Append("| Consumer | Theme | Undefined keys | Static | Dynamic |\n|---|---|---:|---:|---:|\n");
        foreach (ConsumerThemeFindings findings in result.Findings)
        {
            List<IGrouping<string, UndefinedKeyFinding>> byKey = findings.Undefined
                .GroupBy(f => f.Key, StringComparer.Ordinal)
                .ToList();
            int statics = byKey.Count(g => g.First().WorstKind == ReferenceKind.Static);
            sb.Append("| ").Append(Cell(findings.Consumer.Config.Name))
              .Append(" | ").Append(Cell(findings.Theme.Config.Name))
              .Append(" | ").Append(byKey.Count.ToString(CultureInfo.InvariantCulture))
              .Append(" | ").Append(statics.ToString(CultureInfo.InvariantCulture))
              .Append(" | ").Append((byKey.Count - statics).ToString(CultureInfo.InvariantCulture))
              .Append(" |\n");
        }

        sb.Append('\n');

        foreach (ConsumerThemeFindings findings in result.Findings)
        {
            if (findings.Undefined.Count == 0)
            {
                continue;
            }

            sb.Append("### ").Append(findings.Consumer.Config.Name).Append(" under ").Append(findings.Theme.Config.Name).Append("\n\n");
            sb.Append("| Key | Reference | Variants |\n|---|---|---|\n");

            int audited = findings.Theme.Variants.Count;
            foreach (IGrouping<string, UndefinedKeyFinding> group in findings.Undefined
                         .GroupBy(f => f.Key, StringComparer.Ordinal)
                         .OrderBy(g => g.Key, StringComparer.Ordinal))
            {
                List<string> variants = findings.Theme.Variants.Where(v => group.Any(f => f.DisplayName == v)).ToList();
                string kind = group.First().WorstKind == ReferenceKind.Static ? "static (throws)" : "dynamic (invisible)";
                sb.Append("| ").Append(Code(group.Key))
                  .Append(" | ").Append(kind)
                  .Append(" | ").Append(variants.Count == audited ? "all" : Cell(string.Join(", ", variants)))
                  .Append(" |\n");
            }

            sb.Append('\n');
        }
    }

    private static void RenderContrast(StringBuilder sb, AuditResult result)
    {
        sb.Append("## Contrast\n\n");
        sb.Append("WCAG 2.x contrast ratio per pair and variant, the background composited over its `over` key ")
          .Append("first. A ratio in bold is below the pair's floor; `n/a` could not be measured and is explained ")
          .Append("under the table.\n\n");

        bool any = false;
        foreach (ConsumerThemeFindings findings in result.Findings)
        {
            if (findings.Contrast.Count == 0)
            {
                continue;
            }

            any = true;
            IReadOnlyList<string> variants = findings.Theme.Variants;
            IReadOnlyList<ContrastPair> pairs = findings.Consumer.Pairs;

            int pass = findings.Contrast.Count(f => f.Status == ContrastStatus.Pass);
            int fail = findings.Contrast.Count(f => f.Status == ContrastStatus.Fail);
            int unscored = findings.Contrast.Count(f => f.Status == ContrastStatus.Unscored);

            sb.Append("### ").Append(findings.Consumer.Config.Name).Append(" under ").Append(findings.Theme.Config.Name).Append("\n\n");
            sb.Append(pairs.Count.ToString(CultureInfo.InvariantCulture)).Append(" pairs × ")
              .Append(variants.Count.ToString(CultureInfo.InvariantCulture)).Append(" variants: ")
              .Append(pass.ToString(CultureInfo.InvariantCulture)).Append(" pass, ")
              .Append(fail.ToString(CultureInfo.InvariantCulture)).Append(" below the floor, ")
              .Append(unscored.ToString(CultureInfo.InvariantCulture)).Append(" not measurable.\n\n");

            sb.Append("| Foreground | Background | Floor |");
            foreach (string variant in variants)
            {
                sb.Append(' ').Append(Cell(variant)).Append(" |");
            }

            sb.Append("\n|---|---|---:|");
            foreach (string _ in variants)
            {
                sb.Append("---:|");
            }

            sb.Append('\n');

            List<ContrastFinding> unscoredFindings = [];
            foreach (ContrastPair pair in pairs)
            {
                string background = pair.Over is null ? Code(pair.Background) : Code(pair.Background) + " over " + Code(pair.Over);
                sb.Append("| ").Append(Code(pair.Foreground))
                  .Append(" | ").Append(background)
                  .Append(" | ").Append(pair.Floor.ToString("0.0", CultureInfo.InvariantCulture))
                  .Append(" |");
                foreach (string variant in variants)
                {
                    ContrastFinding finding = findings.Contrast.First(f => f.DisplayName == variant && ReferenceEquals(f.Pair, pair));
                    sb.Append(' ').Append(Ratio(finding)).Append(" |");
                    if (finding.Status == ContrastStatus.Unscored)
                    {
                        unscoredFindings.Add(finding);
                    }
                }

                sb.Append('\n');
            }

            sb.Append('\n');
            if (unscoredFindings.Count > 0)
            {
                foreach (ContrastFinding finding in unscoredFindings)
                {
                    sb.Append("- ").Append(Code(finding.Pair.Foreground)).Append(" on ").Append(Code(finding.Pair.Background))
                      .Append(" under ").Append(finding.DisplayName).Append(": ").Append(finding.Reason).Append('\n');
                }

                sb.Append('\n');
            }
        }

        if (!any)
        {
            sb.Append(None).Append("\n\n");
        }
    }

    private static string Ratio(ContrastFinding finding)
    {
        return finding.Status switch
        {
            ContrastStatus.Pass => finding.Ratio!.Value.ToString("0.00", CultureInfo.InvariantCulture),
            ContrastStatus.Fail => "**" + finding.Ratio!.Value.ToString("0.00", CultureInfo.InvariantCulture) + "**",
            _ => "n/a",
        };
    }

    private static string RelativeIfInside(AuditConfig config, string path)
    {
        string relative = config.Relative(path);
        return relative.StartsWith("..", StringComparison.Ordinal) ? Path.GetFileName(path) : relative;
    }

    private static string Code(string text)
    {
        return "`" + text.Replace("|", "\\|", StringComparison.Ordinal) + "`";
    }

    private static string Cell(string text)
    {
        return text.Replace("|", "\\|", StringComparison.Ordinal);
    }
}
