using System.Xml.Linq;
using Bennewitz.Ninja.XamlQuality.ThemeAudit;

namespace XamlQuality.Tests.ThemeAudit;

/// <summary>
/// The compat generator on the committed fixture under <c>Fixtures/compat</c>: a Fluent-shaped
/// source with Default and Dark, a Semi-shaped target with a high-contrast variant, and a mapping
/// that exercises every path — mapped, copied, literal fallback, restored, skipped by policy,
/// skipped for a bad mapping — then proves the merged result leaves a source-templated consumer
/// with nothing undefined.
/// </summary>
public sealed class CompatGeneratorTests : IDisposable
{
    private static readonly XNamespace Avalonia = "https://github.com/avaloniaui";
    private static readonly XNamespace Xaml = "http://schemas.microsoft.com/winfx/2006/xaml";

    private readonly string _fixture = FixturePaths.Fixture("compat");
    private readonly string _root = Directory.CreateTempSubdirectory("theme-compat-").FullName;

    public void Dispose()
    {
        Directory.Delete(_root, recursive: true);
    }

    [Fact]
    public void Generates_mapped_copied_literal_and_restored_entries_and_skips_what_it_must()
    {
        (ThemeInventory from, ThemeInventory to, CompatMapping mapping) = Load();

        CompatGeneration generation = CompatGenerator.Generate(from, to, mapping, "From", "To");

        // Deterministic.
        Assert.Equal(generation.Xml, CompatGenerator.Generate(from, to, mapping, "From", "To").Xml);

        CompatEntry Entry(string variant, string key) => Assert.Single(generation.Entries, e => e.Variant == variant && e.Key == key);
        CompatSkipped Skipped(string variant, string key) => Assert.Single(generation.Skipped, s => s.Variant == variant && s.Key == key);

        // Mapped: a colour onto the target's colour, with the reviewer's reason carried.
        Assert.Equal(CompatHow.Mapped, Entry("Light", "SysInk").How);
        Assert.Equal("ToInkColor — primary ink", Entry("Light", "SysInk").Detail);
        Assert.Equal(CompatHow.Mapped, Entry("Dark", "HighlightColor").How);
        Assert.Equal(CompatHow.Mapped, Entry("Light", "AccentColor").How); // supplied by a code provider

        // Copied verbatim: an alias chain, a translucent literal, a brush with opacity, a thickness, a converter.
        Assert.Equal(CompatHow.Copied, Entry("Light", "SysInkBrush").How);
        Assert.Equal(CompatHow.Copied, Entry("Light", "ButtonFg").How);
        Assert.Equal(CompatHow.Copied, Entry("Dark", "SysAlpha").How);
        Assert.Equal(CompatHow.Copied, Entry("Light", "Ghost").How);
        Assert.Equal("Thickness", Entry("Light", "Pad").Detail);
        Assert.Equal("using:Avalonia.Controls.Converters:MarginMultiplierConverter", Entry("Light", "Mult").Detail);

        // Literal fallback: the brush aliases SysInk (fine) but its opacity references nothing; it resolves to a colour, so it is written out.
        Assert.Equal(CompatHow.Literal, Entry("Light", "DanglingButColour").How);
        Assert.Contains("NopeOpacity", Entry("Light", "DanglingButColour").Detail);

        // Restored: Vivid defines its own HighlightColor, which the Dark compat entry would shadow.
        Assert.Equal(CompatHow.Restored, Entry("Vivid", "HighlightColor").How);
        Assert.DoesNotContain(generation.Entries, e => e.Variant == "Vivid" && e.Key != "HighlightColor");

        // Skipped: dangling and not a colour; a template by policy; a mapping to nothing; a colour mapped to a brush.
        Assert.Contains("Nope", Skipped("Light", "Dangling").Reason);
        Assert.Contains("policy", Skipped("Light", "FancyTheme").Reason);
        Assert.Contains("NoSuchTarget", Skipped("Light", "BadMap").Reason);
        Assert.Contains("brush", Skipped("Light", "WrongKind").Reason);

        // Not generated at all: a key the target already defines.
        Assert.DoesNotContain(generation.Entries, e => e.Key == "AlreadyThere");
        Assert.DoesNotContain(generation.Skipped, s => s.Key == "AlreadyThere");
    }

    [Fact]
    public void Writes_a_well_formed_dictionary_with_the_target_variant_keys_and_the_prefixes_it_uses()
    {
        (ThemeInventory from, ThemeInventory to, CompatMapping mapping) = Load();
        CompatGeneration generation = CompatGenerator.Generate(from, to, mapping, "From", "To");

        XDocument document = XDocument.Parse(generation.Xml);
        XElement root = document.Root!;
        Assert.Equal(Avalonia + "ResourceDictionary", root.Name);
        Assert.StartsWith(" Generated by theme-audit compat", ((XComment)document.FirstNode!).Value);

        // Prefixes: x always; conv and fx because the output uses them; nothing unused.
        Dictionary<string, string> declared = root.Attributes().Where(a => a.IsNamespaceDeclaration && a.Name.LocalName != "xmlns")
            .ToDictionary(a => a.Name.LocalName, a => a.Value, StringComparer.Ordinal);
        Assert.Equal("http://schemas.microsoft.com/winfx/2006/xaml", declared["x"]);
        Assert.Equal("using:Avalonia.Controls.Converters", declared["conv"]);
        Assert.Equal("using:Fixture", declared["fx"]);
        Assert.Equal(3, declared.Count);

        // One dictionary per target variant, keyed as the target declares them, in mapping order then restored.
        List<XElement> dictionaries = root.Element(Avalonia + "ResourceDictionary.ThemeDictionaries")!.Elements().ToList();
        Assert.Equal(["Light", "Dark", "{x:Static fx:Theme.Vivid}"], dictionaries.Select(d => d.Attribute(Xaml + "Key")!.Value).ToArray());

        // The mapped colour is an alias element; the mapped brush-from-colour form is not needed here; the copied converter keeps its attributes.
        XElement defaultDictionary = dictionaries[0];
        XElement sysInk = defaultDictionary.Elements().Single(e => e.Attribute(Xaml + "Key")?.Value == "SysInk");
        Assert.Equal("StaticResource", sysInk.Name.LocalName);
        Assert.Equal("ToInkColor", sysInk.Attribute("ResourceKey")!.Value);
        XElement mult = defaultDictionary.Elements().Single(e => e.Attribute(Xaml + "Key")?.Value == "Mult");
        Assert.Equal("16", mult.Attribute("Indent")!.Value);
        XElement ghost = defaultDictionary.Elements().Single(e => e.Attribute(Xaml + "Key")?.Value == "Ghost");
        Assert.Equal("0.5", ghost.Attribute("Opacity")!.Value);

        // Entries are sorted by key; the file ends with one newline and uses LF only.
        List<string> keys = defaultDictionary.Elements().Select(e => e.Attribute(Xaml + "Key")!.Value).ToList();
        Assert.Equal(keys.Order(StringComparer.Ordinal), keys);
        Assert.EndsWith("</ResourceDictionary>\n", generation.Xml);
        Assert.DoesNotContain("\r", generation.Xml);
    }

    [Fact]
    public void Merged_over_the_target_the_dictionary_leaves_a_source_templated_consumer_nothing_undefined()
    {
        (ThemeInventory from, ThemeInventory to, CompatMapping mapping) = Load();
        CompatGeneration generation = CompatGenerator.Generate(from, to, mapping, "From", "To");

        string generated = Path.Combine(_root, "FromKeys.To.axaml");
        File.WriteAllText(generated, generation.Xml);

        ThemeInventory merged = ThemeInventory.Build(new ThemeSource(Path.Combine(_fixture, "To.axaml"), _fixture)
        {
            Inheritance = Inheritance(),
            Merge = [generated],
        });

        IReadOnlyList<ResourceReference> references = ResourceReferenceScanner.Scan(Path.Combine(_fixture, "consumer"));
        Assert.Empty(ThemeAuditFindings.UndefinedKeys(references, merged, ["Light", "Dark", "Vivid"]));

        // Without the dictionary, the same consumer is broken under every variant.
        IReadOnlyList<UndefinedKeyFinding> before = ThemeAuditFindings.UndefinedKeys(references, to, ["Light", "Dark", "Vivid"]);
        Assert.Equal(["AccentColor", "ButtonFg", "HighlightColor", "Mult", "Pad", "SysAlpha"], before.Select(f => f.Key).Distinct().Order(StringComparer.Ordinal).ToArray());

        // The mapped colour follows the target's palette; the restored key keeps Vivid's own value.
        Assert.Equal(new AuditColor(0xFF, 0xF9, 0xF9, 0xF9), merged.ForVariant("Dark").Resolve("SysInk"));
        Assert.Equal(new AuditColor(0xFF, 0x1C, 0x1F, 0x23), merged.ForVariant("Light").Resolve("ButtonFg"));
        Assert.Equal(new AuditColor(0xFF, 0x54, 0xA9, 0xFF), merged.ForVariant("Dark").Resolve("HighlightColor"));
        Assert.Equal(new AuditColor(0xFF, 0xD6, 0xB4, 0xFD), merged.ForVariant("Vivid").Resolve("HighlightColor"));
    }

    [Fact]
    public void A_custom_variant_can_be_keyed_through_a_stand_in_type()
    {
        (ThemeInventory from, ThemeInventory to, CompatMapping mapping) = Load();
        VariantKeyStyle standIn = new() { Prefix = "dv", Namespace = "using:Consumer.Theming", Type = "HostVariants" };

        CompatGeneration generation = CompatGenerator.Generate(from, to, mapping, "From", "To", standIn);

        XElement root = XDocument.Parse(generation.Xml).Root!;
        Dictionary<string, string> declared = root.Attributes().Where(a => a.IsNamespaceDeclaration && a.Name.LocalName != "xmlns")
            .ToDictionary(a => a.Name.LocalName, a => a.Value, StringComparer.Ordinal);
        Assert.Equal("using:Consumer.Theming", declared["dv"]);
        Assert.False(declared.ContainsKey("fx")); // the theme's own prefix is no longer needed

        List<string> keys = root.Element(Avalonia + "ResourceDictionary.ThemeDictionaries")!.Elements()
            .Select(d => d.Attribute(Xaml + "Key")!.Value).ToList();
        Assert.Equal(["Light", "Dark", "{x:Static dv:HostVariants.Vivid}"], keys);
    }

    [Fact]
    public void The_shipped_mappings_load_by_bare_name()
    {
        AuditConfig config = AuditConfig.Parse("""{ "themes": [] }""", _root);
        foreach (string name in new[] { "FluentToSemi", "SimpleToSemi" })
        {
            CompatMapping mapping = CompatMapping.Load(CompatMapping.Locate(config, name));
            Assert.Equal(name + ".json", mapping.Name);
            Assert.Equal(["Default", "Dark"], mapping.Variants.Keys.ToArray());
            Assert.NotEmpty(mapping.Keys);
            Assert.All(mapping.Keys.Values, target => Assert.NotNull(target.Why));
        }
    }

    private (ThemeInventory From, ThemeInventory To, CompatMapping Mapping) Load()
    {
        // AccentColor is supplied by code in the real Fluent; the fixture file has no provider
        // element, so wrap it in an entry that includes it (by a relative path — a leading slash
        // would mean "rooted at the base directory") and declares the provider.
        string providerEntry = Path.Combine(_root, "FromWithProvider.axaml");
        string relativeFrom = Path.GetRelativePath(_root, Path.Combine(_fixture, "From.axaml")).Replace('\\', '/');
        File.WriteAllText(providerEntry,
            """
            <ResourceDictionary xmlns="https://github.com/avaloniaui"
                                xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                                xmlns:accents="using:Fixture.Accents">
              <ResourceDictionary.MergedDictionaries>
                <ResourceInclude Source="FROM" />
                <accents:SystemAccentColors />
              </ResourceDictionary.MergedDictionaries>
            </ResourceDictionary>
            """.Replace("FROM", relativeFrom, StringComparison.Ordinal));
        ThemeInventory from = ThemeInventory.Build(new ThemeSource(providerEntry, _root)
        {
            Providers = new Dictionary<string, IReadOnlyDictionary<string, string?>>(StringComparer.Ordinal)
            {
                ["SystemAccentColors"] = new Dictionary<string, string?>(StringComparer.Ordinal) { ["AccentColor"] = "#FF0078D7" },
            },
        });

        ThemeInventory to = ThemeInventory.Build(new ThemeSource(Path.Combine(_fixture, "To.axaml"), _fixture) { Inheritance = Inheritance() });
        CompatMapping mapping = CompatMapping.Load(Path.Combine(_fixture, "mapping.json"));
        return (from, to, mapping);
    }

    private static Dictionary<string, string> Inheritance()
    {
        return new Dictionary<string, string>(StringComparer.Ordinal) { ["Vivid"] = "Dark" };
    }
}
